### ISSUE TITLE
Reference error in client.folders.copy

### ISSUE THREAD

**Issue by kksharma1618** [allenmichael/box-javascript-sdk#10]
Error:
ReferenceError: REQUIRED_VALUES is not defined

At this line: https://github.com/allenmichael/box-javascript-sdk/blob/809b03e9af2ac585c3144d09e028ef92a423a75c/src/managers/folders.js#L123

Replacing it by:
```
this._getFolder(options, [MODEL_VALUES.PARENT, MODEL_VALUES.ID, MODEL_VALUES.NAME], skipValidation, ignoreModelValues);
```
works.

**Comment by allenmichael** [comment]
@kksharma1618 This is resolved with the new build. Sorry about the wait!
