### ISSUE TITLE
Data returned by client is different in ie11 and other browsers

### ISSUE THREAD

**Issue by kksharma1618** [allenmichael/box-javascript-sdk#11]
Example, to get root items we are using:
``` js
client.folders.getItems({
    id: '0',
    params: {
        fields: 'id,type,name,created_at,modified_at,size,path_collection,permissions,parent',
        limit: 10
    }
}).then(function(r) { console.log("r", r); }, function(e) { console.log("e", e); });
```
where client is an authenticated BasicBoxClient

In all other browsers it results in:
```
r {total_count: 18, entries: Array(10), offset: 0, limit: 10, order: Array(2)}
```
In ie11, there is no promise support, and we are using a promise polyfill https://github.com/stefanpenner/es6-promise 

ie11 results in:
```
r {
    "data": {total_count: 18, entries: Array(10), offset: 0, limit: 10, order: Array(2)},
    "headers": {"content-type": "application/json", ...},
    "status": 200
}
```

In ie11, the data is wrapped in data subfield. Object has headers and status fields too.

**Comment by kksharma1618** [comment]
Issue is in this line https://github.com/allenmichael/box-javascript-sdk/blob/809b03e9af2ac585c3144d09e028ef92a423a75c/src/box-http.js#L90

If window has fetch (not in ie11), then you are using fetch, but transforming the response before passing it to the user: in function constructResponse.

In ie11 there is no fetch, and so you are directly passing response in this format:
```
{
            data: returnData,
            headers: headers,
            status: this.status
          }
```
Wrapping that line with constructResponse should fix the issue.

**Comment by allenmichael** [comment]
@kksharma1618 I took a stab with fixing this according to your recommendation, but I don't have a readily available IE11 installation to test. Let me know if this resolved the issue, and I'll close.

**Comment by allenmichael** [comment]
Closing. Please reopen if the issue persists.
