### ISSUE TITLE
Fix for https://github.com/allenmichael/box-javascript-sdk/issues/11 broke chunkedUpload

### ISSUE THREAD

**Issue by kittimiyo** [allenmichael/box-javascript-sdk#14]
After the fix applied in issue 11, chunkedUpload has started throwing an error: `response.json is not a function`

![image](https://user-images.githubusercontent.com/3441699/44491545-752a5500-a616-11e8-961c-6a30b7c1e945.png)

**Comment by allenmichael** [comment]
Yikes! I fixed the issue. The HTTP layer should be fixed now.

**Comment by kittimiyo** [comment]
Thank you!
