### ISSUE TITLE
ChunkedUpload returns {} on a 202 response to commitUpload

### ISSUE THREAD

**Issue by a801227** [allenmichael/box-javascript-sdk#15]
The "resp" object passed to the "then" block at chunked-uploader.js:468 is an empty object when the server returns a 202. 
- 202 status if-block is bypassed and commit never happens. 
- ChunkedUpload returns an empty object.

Probably a result of the previous issue fix?

---------
Side-note: Works ok if I hold the code execution to delay makeRequest.

**Comment by allenmichael** [comment]
I'll dig in to this in a day or two! Sorry for the inconvenience.

**Comment by a801227** [comment]
Any updates?

**Comment by allenmichael** [comment]
I honestly thought I had already pushed the fix! Sorry about that, got a lot of in-flight projects at the moment so I got a little scatterbrained here. Hope the fix works! I tested in Chrome with vanilla JS and a 50MB file.

**Comment by a801227** [comment]
basic-box-client::make_request#17
> options = this._formatOptions(options); 

This function stripped your includeFullResponse property, so I am still getting the {} if 202 is returned during commitUpload.

**Comment by allenmichael** [comment]
Once again with feeling: commit id -- 9d809af

**Comment by a801227** [comment]
Looks like the commit created a new problem...

![image](https://user-images.githubusercontent.com/12674776/45971983-4e818480-bfef-11e8-9aa4-071a05543fcd.png)

{"code":"invalid_json","message":"Request body was not valid JSON","request_id":"e4397c04cff017dab2300def49af2580"}

**Comment by allenmichael** [comment]
thank you for your patience down this load and winding road! everything is in order now. it was a simple JSON error address in #bfb8f5f

**Comment by a801227** [comment]
Fix looks good. Thanks!
