### ISSUE TITLE
Chunk upload is not working as expected

### ISSUE THREAD

**Issue by mustak67** [allenmichael/box-javascript-sdk#16]
Hi Team,
The chunk upload process always throws me a error like "File size less than minimum allowed for this API: 50000000", even if the file size is greater that the reported size.

Kindly assist me.

Thanks,
Mustak
[
![error-in-sdk](https://user-images.githubusercontent.com/11425808/45557796-05496c00-b85c-11e8-8f14-d9d51717dcdc.PNG)
](url)

**Comment by allenmichael** [comment]
You are sending in a FileList object. The method call requires a File object. You cannot send an array to the chunkedUpload method.

**Comment by allenmichael** [comment]
you can use a foreach on your FileList:

```
const promises = [];
list.forEach(f => {
  promises.push(client.files.chunkedUpload({
    file: f,
    name: f.name,
    parentFolder: { id: '0' }
  }));
});
Promise.all(promises)
  .then(results => { console.log(results); });
```
