### ISSUE TITLE
(files.)getThumbnail returns {} on success

### ISSUE THREAD

**Issue by a801227** [allenmichael/box-javascript-sdk#18]
Perhaps getThumbnail needs a "includeFullResponse" too.
I would expect at least the URL to be returned.

**Comment by allenmichael** [comment]
This functionality should be removed from the SDK according to what I found when investigating for issue #8. I will remove this method and close this issue once the method is no longer in the SDK.

**Comment by a801227** [comment]
![image](https://user-images.githubusercontent.com/12674776/46979931-dc4d0e80-d087-11e8-9fc4-911b37dbf1de.png)

I don't think this method should be removed. It appears that while 302 is returned for generic icons (e.g. pdf), 200 is returned for image files, so it should at least still work when it matters.

**Comment by allenmichael** [comment]
Leaving as is for the time being then! Feel free to reopen if anything changes.
