### ISSUE TITLE
client.files.chunkedUpload is undefined

### ISSUE THREAD

**Issue by MatiasFito** [allenmichael/box-javascript-sdk#2]
Hi, i'm having an issue with the new functionallity for chunkedUpload, i see the code is in the source code, but when i do the npm run build and include the resulting BoxSdk.min.js to my html the method is not available, could it be that an include in the webpack is missing?. Thanks in advance!

**Comment by allenmichael** [comment]
Hi Matias,

I'm not sure what's going on with your build issues, but I'm have no issues when building and using the chunkedUpload method on the Files manager. I've just updated the repo with a build that I've confirmed has no issues when accessing the chunkedUpload method on the Files manager. Would you mind trying that build and seeing if you have the same issue?

Thanks,
AM

**Comment by MatiasFito** [comment]
Sure i'll give it a go and let you know, thanks!

**Comment by MatiasFito** [comment]
It's working now, both with your file and building it through npm, probably it was a cache thing with my app that was using the old version of this SDK. Thanks!
