### ISSUE TITLE
Change file name upon new version upload not working

### ISSUE THREAD

**Issue by dyspark** [allenmichael/box-javascript-sdk#20]
Hi, I am trying to change the file name when uploading a new version, and can't seem to figure out why it's not working. Below is what I have tried:

`let formData = new FormData();
 const fileName = 'newName';
 formData.append('fileId', contentId);
 formData.append('name', fileName);
 this.boxClient.files.uploadNewFileVersion({ body: formData })`

**Comment by allenmichael** [comment]
hi there,

this was pretty difficult to track down! apparently you have to have an 'attributes' item appended to the formdata object. i put a new example on the README. here's how to format your formdata:

```javascript
var formData = new FormData();
formData.append('file', files[0]);
formData.append('id', '335561149042');
formData.append('attributes', '{"name": "newlaser.jpg"}');
```
