### ISSUE TITLE
how to get error.respose.status

### ISSUE THREAD

**Issue by Band-Aid** [allenmichael/box-javascript-sdk#21]
Hi, 
I'm trying to write an exception to detect expired Access tokens.
I can't get the status code from the err object. Is there anyway to get the status code?

```
catch(function (err){
  //err.response.status (undefined)
 //err.status(undefined)
  err.message (unauthorized)
})
```

**Comment by allenmichael** [comment]
i had a bug in the error handling for 401 responses, but i just pushed a fix that should resolve it. 

you should be able to use `err.response.status` now. let me know if it's fixed!
