### ISSUE TITLE
Cancel in progress upload?

### ISSUE THREAD

**Issue by MatiasFito** [allenmichael/box-javascript-sdk#3]
Hi, i've been reading the docs and source code and i can't find a way to manually cancel a chunk request. It would be useful to do so in our app when the user makes certain actions, like pressing a cancel button or leaving the page. Is there a way to do it currently implemented that i did not find?. Thanks!

**Comment by allenmichael** [comment]
Hey Matias, I haven't implemented that functionality yet. I worked on it this past weekend and have it functioning. I'll push up the code later today after cleaning things up a bit.

**Comment by MatiasFito** [comment]
Great news Michael!, looking forward to test it, and thanks for all your hard work this SDK is very useful for our project.

**Comment by MatiasFito** [comment]
Already in place and working, looks great!
