### ISSUE TITLE
Implementing chunk upload for uploadNewFileVersion

### ISSUE THREAD

**Issue by MatiasFito** [allenmichael/box-javascript-sdk#5]
Hi, i've noticed that the chunked uploader can only be used for uploading new files, but replacing an existing file with the chunked upload throws an "element already exists" error, and the endpoint for uploadNewFileVersion uses the regular upload, is it possible to use the multipart/chunked logic for the newFileVersion?. Thanks!

**Comment by allenmichael** [comment]
Hey Matias, just added a method for using chunked upload with a new version of an existing file:
https://github.com/allenmichael/box-javascript-sdk#upload-new-version-of-a-file-greater-than-50mb-with-chunking

**Comment by MatiasFito** [comment]
Excelent i was looking through it and it's just what we needed. Thanks again!
