### ISSUE TITLE
build doesn't work when installed inside another project

### ISSUE THREAD

**Issue by neocolmartin** [allenmichael/box-javascript-sdk#6]
The web app in which I am trying to use box-javascript-sdk is already in an npm project. I tried adding this line to my package.json:

```
    "box-javascript-sdk": "https://github.com/allenmichael/box-javascript-sdk.git",
```

then from my app executed`npm install` so that it would pull down the box-javascript-sdk dependency. I then executed:

* `cd node_modules/box-javascript-sdk`
* `npm install` (for good measure)
* `npm run build`

but it failed to build with this error:

```
ERROR in BoxSdk.min.js from UglifyJs
Unexpected token: name (Manager) [./src/managers/manager.js:19,0][BoxSdk.min.js:136,6]
```

I've attached the npm-debug.log file.
[npm-debug-log.txt](https://github.com/allenmichael/box-javascript-sdk/files/1310599/npm-debug-log.txt)

There is a BoxSdk.min.js file in the "lib" folder, but due to the build failure I don't have any confidence in it being correct. It is not minimised, and the line that failed is this:

```
class Metadata extends __WEBPACK_IMPORTED_MODULE_4__manager__["a" /* default */] {
```

which doesn't look Babel has compiled the code int he way that it should.

When I tried cloning the project directly and building it, it completed without errors.

Are there any suggestions on how to manage the dependency on this from a project that is already an npm package? Especially one that already uses Webpack and Babel, as mine does? And are there any suggestions on how to deal with this particular error?

**Comment by allenmichael** [comment]
It sounds like there might be a mismatch with the version of webpack your project uses and the version used for this SDK. I can look at trying to get the build to function automatically with the methodology you've described. 

For the meantime, you can use the minified file from the build directory in this repo or clone the repo and run the build for the SDK.

I'll leave this issue open until I do some more investigation.

**Comment by neocolmartin** [comment]
The version of webpack my project uses is 2.4.1. Looking at your package.json now, I see you're depending on `^3.4.1`. I would have expected npm to indicate that there was a mismatch, but I didn't see such an error (I might have missed it).
