### ISSUE TITLE
Use of search function

### ISSUE THREAD

**Issue by dcp3450** [allenmichael/box-javascript-sdk#7]
I need the search method to get a folder ID. It appears to be included in the SDK but I'm not clear how to use it.

**Comment by allenmichael** [comment]
You provide an object with keys that map to the JSON the API expects for search:

[https://developer.box.com/v2.0/reference#searching-for-content](https://developer.box.com/v2.0/reference#searching-for-content)

It should look something like this:
```js
boxClient.search.search({
  query: "sales",
  file_extensions: "pdf",
  updated_at_range: "2017-05-15T13:35:01-07:00,2017-05-17T13:35:01-07:00"
})
.then((results) => {
  console.log(results);
})
```
It's not that intuitive that you have to use search.search, but it allows for more methods to be added to the search manager in the future.
