### ISSUE TITLE
Issue with non-JSON responses?

### ISSUE THREAD

**Issue by metabrain** [allenmichael/box-javascript-sdk#8]
Hey,

I am having some issues using the getThumbnail function since I always get an empty object. After debugging into your SDK, I have noticed that it is always trying to parse the responses from web API as a JSON object. However, and according to Box API Reference, the /files/:id/thumbnail..ext endpoint will always return a binary blob of the image.

In this case, when hitting the binary blob, an exception will be thrown while transforming into JSON, no error will be printed to the console, and a simply empty object is returned to the user... 

Here is piece of the offending code:

  function constructResponse(response) {
    if (options.includeFullResponse) {
      let buildResponse = {
        data: {},
        headers: {},
        status: ""
      };
      return new Promise(function (resolve, reject) {
        buildResponse.headers = response.headers;
        buildResponse.status = response.status;
        return response.json().catch(() => { return {}; })
          .then(function (body) {
            buildResponse.data = body;
            resolve(buildResponse);
          })
      });
    } else {
      return response.json().catch(() => { return {}; });  /////// HERE
    }
  } 

Cheers,
Daniel

**Comment by metabrain** [comment]
I also tried to set on options "includeFullResponse" to try and skip the JSON-parsing bit but then that option gets removed/"sanitized" by this piece of code: in base-box-client.js

  _checkForEmptyObjects(options) {
    Object.keys(options).map((field) => {
      if (field !== "body" && field !== "upload" && field !== "chunkedUpload" && field !== "useXHR" && field !== "returnCancelToken" && field !== "returnsOnlyOptions" && this._isEmpty(options[field])) {
        delete options[field];
      }
    });
  }

Cheers,
Dan

**Comment by allenmichael** [comment]
@metabrain Thank you so much for the in-depth error tracing you've included! Since this library is very much a labor of love, I haven't had as much time as I'd like to dedicate to checking issues and updating. I'll make this a priority to get fixed in the next two weeks, or, I'd be very happy to review a pull request if you're interested in trying to tackle this as well. I appreciate the patience and I'm sorry for being slow to respond!

**Comment by metabrain** [comment]
@allenmichael no worries, I don't mind trying to fix it myself ;)

I do not do a lot of frontend dev nowadays so my knowledge of these new build tools is quite limited. Can you just point me how I can compile/build your package so I can try to fix the source code itself? So far I have been debugging + trying fixes on the minified source itself which is not optimal, to say the least haha

Cheers,
Dan

**Comment by allenmichael** [comment]
@metabrain hey! sorry for the delay. so i looked into this more, and unfortunately the call to the get thumbnail endpoint uses a 302 redirect to the Box CDN that the ajax engine automatically follow. the cdn.box.com address doesn't have CORS settings as an option, so nothing can be returned from a getThumbnail request. Unless i'm missing something here, i'm not sure that the call can ever work. i'll remove the getThumbnail method for now.

**Comment by allenmichael** [comment]
Closing as not possible at this time.
