### ISSUE TITLE
Submission to npmjs.org?

### ISSUE THREAD

**Issue by ajmas** [allenmichael/box-javascript-sdk#9]
The firm I work for only permits JavaScript libraries sourced via npm. Are there any plans to make this project available via npm?

**Comment by depiction** [comment]
+1

**Comment by allenmichael** [comment]
I'm sorry I haven't responded to this one yet. I honestly was thinking it over. I don't think I'll be adding this to NPM anytime soon. It's not an official Box SDK and I'm not an employee at Box, so I don't feel comfortable adding to NPM. If someone at Box wants to add it, I'm definitely okay with that.

So as not to leave you empty handed, NPM actually supports installing packages directly from Github.

`npm install --save allenmichael/box-javascript-sdk`

You can then add to your HTML page like this:
`<script src="node_modules/box-javascript-sdk/build/BoxSdk.min.js" type="text/javascript"></script>`
